version: "3.0"

services:
  app:
    image: "soroosh-tanzadeh/authentication-service"
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    entrypoint: "java -jar /app/authentication-service.jar"
    volumes:
      - "certificate:/app/certificate"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/authentication"
      SPRING_DATASOURCE_USERNAME: "soroosh"
      SPRING_DATASOURCE_PASSWORD: "example"
      SPRING_DATASOURCE_driverClassName: "com.mysql.cj.jdbc.Driver"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: soroosh
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: authentication

volumes:
  db: {}
  certificate: {}