version: "3.0"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app:rw"
    ports:
      - "8080:8080"
      - "35729:35729"
    entrypoint: "sleep 1d"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/authentication"
      SPRING_DATASOURCE_USERNAME: "soroosh"
      SPRING_DATASOURCE_PASSWORD: "example"
      SPRING_DATASOURCE_driverClassName: "com.mysql.cj.jdbc.Driver"
    depends_on:
      - db
  db:
    image: mariadb:10.5
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: soroosh
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: authentication

volumes:
  db: {}