app: "cloud"
logging.level.org.springframework.security: debug
logging.level.org.springframework.security.web.access.ExceptionTranslationFilter: debug
grpc:
  port: 9595
  service-access-token: "token"
jwt:
  secret: "secret"
restrictions:
  max_app_for_user: 3
  max_user_for_app: 100
  storage_limit: "150Mb"
mail-service:
  default-email: "example@example.com"
server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: NEVER
    include-exception: false
spring:
  data:
    jdbc:
      repositories:
        enabled: false
  mail:
    host: "smtp.example.com"
    port: 587
    username: "example"
    password: "secret"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: "jdbc:mysql://localhost:3333/authentication"
    username: "root"
    password: "passwd"
    dialect: org.hibernate.dialect.MariaDB106Dialect
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: "/api/docs"