// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/dto.proto

package com.soroosh.auth.grpc.dto;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_soroosh_auth_grpc_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_soroosh_auth_grpc_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_soroosh_auth_grpc_RequestUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_soroosh_auth_grpc_RequestUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030src/main/proto/dto.proto\022\025com.soroosh." +
      "auth.grpc\"G\n\004User\022\n\n\002id\030\001 \001(\003\022\021\n\tfirstNa" +
      "me\030\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\016\n\006mobile\030\004 \001" +
      "(\t\"\036\n\013RequestUser\022\017\n\007user_id\030\001 \001(\003B#\n\031co" +
      "m.soroosh.auth.grpc.dtoB\004AuthP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_soroosh_auth_grpc_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_soroosh_auth_grpc_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_soroosh_auth_grpc_User_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Mobile", });
    internal_static_com_soroosh_auth_grpc_RequestUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_soroosh_auth_grpc_RequestUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_soroosh_auth_grpc_RequestUser_descriptor,
        new java.lang.String[] { "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
