// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/dto.proto

package com.soroosh.auth.grpc.dto;

public interface RequestUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.soroosh.auth.grpc.RequestUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
