// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/dto.proto

package com.soroosh.auth.grpc.dto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.soroosh.auth.grpc.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string firstName = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string mobile = 4;</code>
   * @return The mobile.
   */
  java.lang.String getMobile();
  /**
   * <code>string mobile = 4;</code>
   * @return The bytes for mobile.
   */
  com.google.protobuf.ByteString
      getMobileBytes();
}
