name: Java CI with Gradle

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Setup
      run: |
        cp src/main/resources/application.example.yml src/main/resources/application.yml
    - name: Test with Gradle
      run: |
        ./gradlew test
